In [8]:
from pathlib import Path
import pandas as pd
import numpy as np
import sys
ROOT = Path.cwd().parent.parent
sys.path.append(str(ROOT))
from src.loading_data.data_catalogue import DataCatalogue
from src.loading_data.load_data import get_clean_2022, get_master_2022_data, one_hot_encode_frame
from src.perturbation.create_perturbations import create_perturbations, preprocess_perturbation

In [9]:
dc = DataCatalogue()
to_perturb = dc.get_perturbation_vars()
continuous_vars = dc.get_perturbation_core_contins() + dc.get_perturbation_vars()
to_encode_vars = dc.get_perturbation_core_to_encode()
print(f'TO PERTURB:\n{to_perturb}')
print(f'CONTINS:\n{continuous_vars}')
print(f'TO ENCODE:\n{to_encode_vars}')

TO PERTURB:
['Motiva_POP', 'motivd_POP', 'indev', 'indevtry', 'inclus_a', 'inclus_b', 'inclus_c', 'comm1', 'comm2', 'anxious', 'happy', 'lone', 'worthw']
CONTINS:
['Age9', 'NSSEC5', 'Educ6', 'IMD10', 'Child4', 'Motiva_POP', 'motivd_POP', 'indev', 'indevtry', 'inclus_a', 'inclus_b', 'inclus_c', 'comm1', 'comm2', 'anxious', 'happy', 'lone', 'worthw']
TO ENCODE:
['Gend3', 'Eth7', 'WorkStat8', 'HHLiv9']

In [10]:
df = get_clean_2022()
X_train, X_test, Y_train, Y_test, test_set_clusters, scaler = preprocess_perturbation(df, 'rf', 'LCA_Class', 'MEMS7_ALL', continuous_vars, to_encode_vars)

['Gend3', 'Disab2_POP', 'Age9', 'Eth7', 'NSSEC5', 'Educ6', 'IMD10', 'Child4', 'WorkStat8', 'HHLiv9', 'serial', 'year', 'LCA_Class', 'MEMS7_ALL']
Data loaded with zero missing values.
Loaded primary frame...
Loaded secondary frame...
Merged Frames.
Dropped NAN values
Keep columns : ['Age9', 'Disab2_POP', 'Educ6', 'NSSEC5', 'IMD10', 'Child4', 'Motiva_POP', 'motivd_POP', 'inclus_a', 'inclus_b', 'inclus_c', 'anxious', 'comm1', 'comm2', 'happy', 'indev', 'indevtry', 'lone', 'worthw', 'Gend3_1.0', 'Gend3_2.0', 'Gend3_3.0', 'Eth7_1.0', 'Eth7_2.0', 'Eth7_3.0', 'Eth7_4.0', 'Eth7_5.0', 'Eth7_6.0', 'Eth7_7.0', 'WorkStat8_0.0', 'WorkStat8_1.0', 'WorkStat8_2.0', 'WorkStat8_3.0', 'WorkStat8_4.0', 'WorkStat8_5.0', 'WorkStat8_6.0', 'WorkStat8_7.0', 'HHLiv9_0.0', 'HHLiv9_1.0', 'HHLiv9_2.0', 'HHLiv9_3.0', 'HHLiv9_4.0', 'HHLiv9_5.0', 'HHLiv9_6.0', 'HHLiv9_7.0', 'HHLiv9_8.0']

In [11]:
X_train.head()

,Age9,Disab2_POP,Educ6,NSSEC5,IMD10,Child4,Motiva_POP,motivd_POP,inclus_a,inclus_b,...,WorkStat8_7.0,HHLiv9_0.0,HHLiv9_1.0,HHLiv9_2.0,HHLiv9_3.0,HHLiv9_4.0,HHLiv9_5.0,HHLiv9_6.0,HHLiv9_7.0,HHLiv9_8.0
9825,-0.374488,1.0,-0.499908,-0.589434,1.844387,3.248746,-0.989594,0.152698,-0.142735,-0.250441,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
4034,2.027354,1.0,-0.499908,2.889586,1.032758,-0.545789,-0.989594,1.155926,1.048086,-0.250441,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
189,-0.374488,1.0,-0.499908,-0.589434,-0.184686,0.719056,-0.989594,0.152698,-0.142735,-0.250441,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
2050,-0.374488,1.0,-0.499908,-0.589434,1.032758,0.719056,-0.989594,1.155926,-0.142735,-0.250441,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
12453,-0.974949,1.0,-0.499908,-0.589434,-0.996315,-0.545789,1.210620,0.152698,-0.142735,-1.373580,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [18]:
anxious = X_train['anxious'].values

In [19]:
mask = np.where( anxious > 1.2, True, False)

In [20]:
mask

array([ True, False, False, ..., False, False, False], shape=(2628,))

In [21]:
X_train.loc[mask]

,Age9,Disab2_POP,Educ6,NSSEC5,IMD10,Child4,Motiva_POP,motivd_POP,inclus_a,inclus_b,...,WorkStat8_7.0,HHLiv9_0.0,HHLiv9_1.0,HHLiv9_2.0,HHLiv9_3.0,HHLiv9_4.0,HHLiv9_5.0,HHLiv9_6.0,HHLiv9_7.0,HHLiv9_8.0
9825,-0.374488,1.0,-0.499908,-0.589434,1.844387,3.248746,-0.989594,0.152698,-0.142735,-0.250441,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
2050,-0.374488,1.0,-0.499908,-0.589434,1.032758,0.719056,-0.989594,1.155926,-0.142735,-0.250441,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
9229,-1.575409,1.0,0.334224,2.019831,-0.590500,-0.545789,-0.989594,1.155926,-0.142735,-0.250441,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11062,0.225972,1.0,-0.499908,-0.589434,1.032758,-0.545789,-0.989594,1.155926,-1.333556,-1.373580,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9331,-0.374488,1.0,-0.499908,0.280321,-0.996315,-0.545789,0.110513,0.152698,-0.142735,-0.250441,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11363,-0.974949,1.0,-0.499908,0.280321,-0.996315,0.719056,0.110513,-1.853757,-0.142735,-0.250441,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
4896,-0.974949,1.0,0.334224,-0.589434,-0.996315,-0.545789,0.110513,0.152698,-0.142735,-0.250441,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10949,2.027354,1.0,-0.499908,2.889586,0.626943,-0.545789,-0.989594,0.152698,-1.333556,-0.250441,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8347,0.225972,1.0,1.168356,0.280321,-1.402129,-0.545789,0.110513,-0.850529,1.048086,0.872698,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6768,-0.974949,0.0,-0.499908,-0.589434,1.032758,-0.545789,1.210620,0.152698,-0.142735,1.995837,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [24]:
X_train.columns.get_loc('Educ6')

2

In [25]:
X_train.loc[X_train.columns.get_loc('Educ6')] += 1

KeyError: 2