In [1]:
import pandas as pd
import numpy
from load_data import get_2022_data

In [2]:
df, meta = get_2022_data()
df.head()

Data Collected...
Data Shape: (16748, 116)

,wt_final,wt_time,xStrata,Reg9,LondInOut,LA_2023,Age9,nadult,nchild,Disab3,...,MONTHS_12_BASESOFTBALL_F13,MONTHS_12_LACROSSE_F14,MONTHS_12_GOALBALL_F15,MONTHS_12_HANDBALL_F16,MEMS7_IN_SPORTCOUNT_A01,MEMS7_OUT_SPORTCOUNT_A01,WHOWITHA_SPORTCOUNT_A01,WHOWITHB_SPORTCOUNT_A01,WHOWITHC_SPORTCOUNT_A01,WHOWITHD_SPORTCOUNT_A01
10,0.589497,0.476685,117.0,3.0,1.0,114.0,5.0,1.0,0.0,2.0,...,0.0,0.0,0.0,0.0,NaN,NaN,0.0,0.0,0.0,0.0
33,0.962646,1.165975,129.0,3.0,2.0,126.0,NaN,1.0,0.0,3.0,...,0.0,0.0,0.0,0.0,NaN,NaN,0.0,0.0,0.0,0.0
52,3.840907,3.882306,9.0,3.0,2.0,9.0,3.0,2.0,1.0,3.0,...,0.0,0.0,0.0,0.0,NaN,NaN,0.0,0.0,0.0,0.0
53,1.506097,1.525295,9.0,3.0,2.0,9.0,3.0,1.0,0.0,2.0,...,0.0,0.0,0.0,0.0,NaN,NaN,0.0,0.0,0.0,0.0
54,1.656646,1.347375,132.0,3.0,2.0,129.0,6.0,1.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [38]:
boroughs = df['LA_2023'].unique()

In [59]:
codebook_path = r'C:\Users\fergu\Documents\GitHub\london_sport2\exploration\data\codebook\year_8_codebook.csv'
codebook = pd.read_csv(codebook_path)
def get_la_index():
    for i, v in enumerate(codebook['Variables']):
        if v == 'LA_2023':
            return i, v
idx, value = get_la_index()
codebook = codebook.loc[idx, 'Value_breakdown']
print(idx, value)

54 LA_2023

In [40]:
import ast
codebook = ast.literal_eval(codebook)
for k, v in codebook.items():
    print(k, v)

-99.0 Missing, should have been answered
-98.0 Not applicable: Survey routing
-97.0 Incorrectly multicoded
-96.0 Out of range
-95.0 Cannot give an estimate / Don't know
-94.0 Prefer not to say
1.0 E07000223 Adur
3.0 E07000032 Amber Valley
4.0 E07000224 Arun
5.0 E07000170 Ashfield
6.0 E07000105 Ashford
7.0 E07000200 Babergh
8.0 E09000002 Barking and Dagenham
9.0 E09000003 Barnet
10.0 E08000016 Barnsley
12.0 E07000066 Basildon
13.0 E07000084 Basingstoke and Deane
14.0 E07000171 Bassetlaw
15.0 E06000022 Bath and North East Somerset
16.0 E06000055 Bedford
17.0 E09000004 Bexley
18.0 E08000025 Birmingham
19.0 E07000129 Blaby
20.0 E06000008 Blackburn with Darwen
21.0 E06000009 Blackpool
22.0 E07000033 Bolsover
23.0 E08000001 Bolton
24.0 E07000136 Boston
25.0 E06000058 Bournemouth, Christchurch and Poole
26.0 E06000036 Bracknell Forest
27.0 E08000032 Bradford
28.0 E07000067 Braintree
29.0 E07000143 Breckland
30.0 E09000005 Brent
31.0 E07000068 Brentwood
32.0 E06000043 Brighton and Hove
33.0 E06000023 Bristol, City of
34.0 E07000144 Broadland
35.0 E09000006 Bromley
36.0 E07000234 Bromsgrove
37.0 E07000095 Broxbourne
38.0 E07000172 Broxtowe
39.0 E06000060 Buckinghamshire
40.0 E07000117 Burnley
41.0 E08000002 Bury
42.0 E08000033 Calderdale
43.0 E07000008 Cambridge
44.0 E09000007 Camden
45.0 E07000192 Cannock Chase
46.0 E07000106 Canterbury
48.0 E07000069 Castle Point
49.0 E06000056 Central Bedfordshire
50.0 E07000130 Charnwood
51.0 E07000070 Chelmsford
52.0 E07000078 Cheltenham
53.0 E07000177 Cherwell
54.0 E06000049 Cheshire East
55.0 E06000050 Cheshire West and Chester
56.0 E07000034 Chesterfield
57.0 E07000225 Chichester
58.0 E07000118 Chorley
59.0 E09000001 City of London
60.0 E07000071 Colchester
62.0 E06000052 Cornwall
63.0 E07000079 Cotswold
64.0 E06000047 County Durham
65.0 E08000026 Coventry
67.0 E07000226 Crawley
68.0 E09000008 Croydon
69.0 E07000096 Dacorum
70.0 E06000005 Darlington
71.0 E07000107 Dartford
72.0 E06000015 Derby
73.0 E07000035 Derbyshire Dales
74.0 E08000017 Doncaster
75.0 E06000059 Dorset
76.0 E07000108 Dover
77.0 E08000027 Dudley
78.0 E09000009 Ealing
79.0 E07000009 East Cambridgeshire
80.0 E07000040 East Devon
81.0 E07000085 East Hampshire
82.0 E07000242 East Hertfordshire
83.0 E07000137 East Lindsey
84.0 E06000011 East Riding of Yorkshire
85.0 E07000193 East Staffordshire
86.0 E07000244 East Suffolk
87.0 E07000061 Eastbourne
88.0 E07000086 Eastleigh
90.0 E07000207 Elmbridge
91.0 E09000010 Enfield
92.0 E07000072 Epping Forest
93.0 E07000208 Epsom and Ewell
94.0 E07000036 Erewash
95.0 E07000041 Exeter
96.0 E07000087 Fareham
97.0 E07000010 Fenland
98.0 E07000112 Folkestone and Hythe
99.0 E07000080 Forest of Dean
100.0 E07000119 Fylde
101.0 E08000037 Gateshead
102.0 E07000173 Gedling
103.0 E07000081 Gloucester
104.0 E07000088 Gosport
105.0 E07000109 Gravesham
106.0 E07000145 Great Yarmouth
107.0 E09000011 Greenwich
108.0 E07000209 Guildford
109.0 E09000012 Hackney
110.0 E06000006 Halton
112.0 E09000013 Hammersmith and Fulham
113.0 E07000131 Harborough
114.0 E09000014 Haringey
115.0 E07000073 Harlow
117.0 E09000015 Harrow
118.0 E07000089 Hart
119.0 E06000001 Hartlepool
120.0 E07000062 Hastings
121.0 E07000090 Havant
122.0 E09000016 Havering
123.0 E06000019 Herefordshire, County of
124.0 E07000098 Hertsmere
125.0 E07000037 High Peak
126.0 E09000017 Hillingdon
127.0 E07000132 Hinckley and Bosworth
128.0 E07000227 Horsham
129.0 E09000018 Hounslow
130.0 E07000011 Huntingdonshire
131.0 E07000120 Hyndburn
132.0 E07000202 Ipswich
133.0 E06000046 Isle of Wight
134.0 E06000053 Isles of Scilly
135.0 E09000019 Islington
136.0 E09000020 Kensington and Chelsea
137.0 E07000146 Kings Lynn and West Norfolk
138.0 E06000010 Kingston upon Hull, City of
139.0 E09000021 Kingston upon Thames
140.0 E08000034 Kirklees
141.0 E08000011 Knowsley
142.0 E09000022 Lambeth
143.0 E07000121 Lancaster
144.0 E08000035 Leeds
145.0 E06000016 Leicester
146.0 E07000063 Lewes
147.0 E09000023 Lewisham
148.0 E07000194 Lichfield
149.0 E07000138 Lincoln
150.0 E08000012 Liverpool
151.0 E06000032 Luton
152.0 E07000110 Maidstone
153.0 E07000074 Maldon
154.0 E07000235 Malvern Hills
155.0 E08000003 Manchester
156.0 E07000174 Mansfield
157.0 E06000035 Medway
158.0 E07000133 Melton
160.0 E09000024 Merton
161.0 E07000042 Mid Devon
162.0 E07000203 Mid Suffolk
163.0 E07000228 Mid Sussex
164.0 E06000002 Middlesbrough
165.0 E06000042 Milton Keynes
166.0 E07000210 Mole Valley
167.0 E07000091 New Forest
168.0 E07000175 Newark and Sherwood
169.0 E08000021 Newcastle upon Tyne
170.0 E07000195 Newcastle-under-Lyme
171.0 E09000025 Newham
172.0 E07000043 North Devon
173.0 E07000038 North East Derbyshire
174.0 E06000012 North East Lincolnshire
175.0 E07000099 North Hertfordshire
176.0 E07000139 North Kesteven
177.0 E06000013 North Lincolnshire
178.0 E07000147 North Norfolk
179.0 E06000024 North Somerset
180.0 E08000022 North Tyneside
181.0 E07000218 North Warwickshire
182.0 E07000134 North West Leicestershire
183.0 E06000057 Northumberland
184.0 E07000148 Norwich
185.0 E06000018 Nottingham
186.0 E07000219 Nuneaton and Bedworth
187.0 E07000135 Oadby and Wigston
188.0 E08000004 Oldham
189.0 E07000178 Oxford
190.0 E07000122 Pendle
191.0 E06000031 Peterborough
192.0 E06000026 Plymouth
193.0 E06000044 Portsmouth
194.0 E07000123 Preston
195.0 E06000038 Reading
196.0 E09000026 Redbridge
197.0 E06000003 Redcar and Cleveland
198.0 E07000236 Redditch
199.0 E07000211 Reigate and Banstead
200.0 E07000124 Ribble Valley
201.0 E09000027 Richmond upon Thames
203.0 E08000005 Rochdale
204.0 E07000075 Rochford
205.0 E07000125 Rossendale
206.0 E07000064 Rother
207.0 E08000018 Rotherham
208.0 E07000220 Rugby
209.0 E07000212 Runnymede
210.0 E07000176 Rushcliffe
211.0 E07000092 Rushmoor
212.0 E06000017 Rutland
214.0 E08000006 Salford
215.0 E08000028 Sandwell
218.0 E08000014 Sefton
220.0 E07000111 Sevenoaks
221.0 E08000019 Sheffield
222.0 E06000051 Shropshire
223.0 E06000039 Slough
224.0 E08000029 Solihull
226.0 E07000012 South Cambridgeshire
227.0 E07000039 South Derbyshire
228.0 E06000025 South Gloucestershire
229.0 E07000044 South Hams
230.0 E07000140 South Holland
231.0 E07000141 South Kesteven
233.0 E07000149 South Norfolk
234.0 E07000179 South Oxfordshire
235.0 E07000126 South Ribble
237.0 E07000196 South Staffordshire
238.0 E08000023 South Tyneside
239.0 E06000045 Southampton
240.0 E06000033 Southend-on-Sea
241.0 E09000028 Southwark
242.0 E07000213 Spelthorne
243.0 E07000240 St Albans
244.0 E08000013 St. Helens
245.0 E07000197 Stafford
246.0 E07000198 Staffordshire Moorlands
247.0 E07000243 Stevenage
248.0 E08000007 Stockport
249.0 E06000004 Stockton-on-Tees
250.0 E06000021 Stoke-on-Trent
251.0 E07000221 Stratford-on-Avon
252.0 E07000082 Stroud
253.0 E08000024 Sunderland
254.0 E07000214 Surrey Heath
255.0 E09000029 Sutton
256.0 E07000113 Swale
257.0 E06000030 Swindon
258.0 E08000008 Tameside
259.0 E07000199 Tamworth
260.0 E07000215 Tandridge
261.0 E07000045 Teignbridge
262.0 E06000020 Telford and Wrekin
263.0 E07000076 Tendring
264.0 E07000093 Test Valley
265.0 E07000083 Tewkesbury
266.0 E07000114 Thanet
267.0 E07000102 Three Rivers
268.0 E06000034 Thurrock
269.0 E07000115 Tonbridge and Malling
270.0 E06000027 Torbay
271.0 E07000046 Torridge
272.0 E09000030 Tower Hamlets
273.0 E08000009 Trafford
274.0 E07000116 Tunbridge Wells
275.0 E07000077 Uttlesford
276.0 E07000180 Vale of White Horse
277.0 E08000036 Wakefield
278.0 E08000030 Walsall
279.0 E09000031 Waltham Forest
280.0 E09000032 Wandsworth
281.0 E06000007 Warrington
282.0 E07000222 Warwick
283.0 E07000103 Watford
284.0 E07000216 Waverley
285.0 E07000065 Wealden
286.0 E07000241 Welwyn Hatfield
287.0 E06000037 West Berkshire
288.0 E07000047 West Devon
289.0 E07000127 West Lancashire
290.0 E07000142 West Lindsey
291.0 E07000181 West Oxfordshire
292.0 E07000245 West Suffolk
293.0 E09000033 Westminster
294.0 E08000010 Wigan
295.0 E06000054 Wiltshire
296.0 E07000094 Winchester
297.0 E06000040 Windsor and Maidenhead
298.0 E08000015 Wirral
299.0 E07000217 Woking
300.0 E06000041 Wokingham
301.0 E08000031 Wolverhampton
302.0 E07000237 Worcester
303.0 E07000229 Worthing
304.0 E07000238 Wychavon
305.0 E07000128 Wyre
306.0 E07000239 Wyre Forest
307.0 E06000014 York
308.0 E06000061 North Northamptonshire
309.0 E06000062 West Northamptonshire
310.0 E06000063 Cumberland
311.0 E06000065 North Yorkshire
312.0 E06000066 Somerset
313.0 E06000064 Westmorland and Furness

In [54]:
for b in boroughs:
    name = codebook[b].split(maxsplit = 1)
    print(name)

['E09000014', 'Haringey']
['E09000017', 'Hillingdon']
['E09000003', 'Barnet']
['E09000018', 'Hounslow']
['E09000021', 'Kingston upon Thames']
['E09000024', 'Merton']
['E09000025', 'Newham']
['E09000002', 'Barking and Dagenham']
['E09000006', 'Bromley']
['E09000012', 'Hackney']
['E09000016', 'Havering']
['E09000027', 'Richmond upon Thames']
['E09000013', 'Hammersmith and Fulham']
['E09000022', 'Lambeth']
['E09000028', 'Southwark']
['E09000033', 'Westminster']
['E09000004', 'Bexley']
['E09000007', 'Camden']
['E09000008', 'Croydon']
['E09000019', 'Islington']
['E09000023', 'Lewisham']
['E09000030', 'Tower Hamlets']
['E09000001', 'City of London']
['E09000005', 'Brent']
['E09000009', 'Ealing']
['E09000011', 'Greenwich']
['E09000015', 'Harrow']
['E09000026', 'Redbridge']
['E09000032', 'Wandsworth']
['E09000010', 'Enfield']
['E09000020', 'Kensington and Chelsea']
['E09000029', 'Sutton']
['E09000031', 'Waltham Forest']

In [75]:
def get_la_index():
    for i, v in enumerate(codebook['Variables']):
        if v == 'LA_2023':
            return i, v

def map_boroughs():
    stacks = []
    codebook_path = r'C:\Users\fergu\Documents\GitHub\london_sport2\exploration\data\codebook\year_8_codebook.csv'
    df, meta = get_2022_data()
    boroughs = df['LA_2023'].unique()
    codebook = pd.read_csv(codebook_path)
    idx, value = get_la_index()
    codebook = codebook.loc[idx, 'Value_breakdown']
    codebook = ast.literal_eval(codebook)
    for b in boroughs:
        data = codebook[b].split(maxsplit=1)
        id = b 
        lad_code = data[0]
        lad_name = data[1]
        vars = [id, lad_code, lad_name]
        stacks.append(vars)
    output = pd.DataFrame(stacks, columns = ['id', 'lad_code', 'lad_name'])
    return output

mapped_boroughs = map_boroughs()
mapped_boroughs.to_csv('london_lads.csv', index=False)

Data Collected...
Data Shape: (16748, 116)

In [76]:
mapped_boroughs.head()

      id   lad_code              lad_name
0  114.0  E09000014              Haringey
1  126.0  E09000017            Hillingdon
2    9.0  E09000003                Barnet
3  129.0  E09000018              Hounslow
4  139.0  E09000021  Kingston upon Thames

In [88]:
diversity_path = r'C:\Users\fergu\Documents\GitHub\london_sport2\exploration\data\boroughs\census2021-ts021-ltla.csv'
diversity = pd.read_csv(diversity_path)
diversity.columns

Index(['date', 'geography', 'geography code',
       'Ethnic group: Total: All usual residents',
       'Ethnic group: Asian, Asian British or Asian Welsh',
       'Ethnic group: Asian, Asian British or Asian Welsh: Bangladeshi',
       'Ethnic group: Asian, Asian British or Asian Welsh: Chinese',
       'Ethnic group: Asian, Asian British or Asian Welsh: Indian',
       'Ethnic group: Asian, Asian British or Asian Welsh: Pakistani',
       'Ethnic group: Asian, Asian British or Asian Welsh: Other Asian',
       'Ethnic group: Black, Black British, Black Welsh, Caribbean or African',
       'Ethnic group: Black, Black British, Black Welsh, Caribbean or African: African',
       'Ethnic group: Black, Black British, Black Welsh, Caribbean or African: Caribbean',
       'Ethnic group: Black, Black British, Black Welsh, Caribbean or African: Other Black',
       'Ethnic group: Mixed or Multiple ethnic groups',
       'Ethnic group: Mixed or Multiple ethnic groups: White and Asian',
       'Ethnic group: Mixed or Multiple ethnic groups: White and Black African',
       'Ethnic group: Mixed or Multiple ethnic groups: White and Black Caribbean',
       'Ethnic group: Mixed or Multiple ethnic groups: Other Mixed or Multiple ethnic groups',
       'Ethnic group: White',
       'Ethnic group: White: English, Welsh, Scottish, Northern Irish or British',
       'Ethnic group: White: Irish',
       'Ethnic group: White: Gypsy or Irish Traveller',
       'Ethnic group: White: Roma', 'Ethnic group: White: Other White',
       'Ethnic group: Other ethnic group',
       'Ethnic group: Other ethnic group: Arab',
       'Ethnic group: Other ethnic group: Any other ethnic group'],
      dtype='str')

In [89]:
cols = [
    'geography',
    'geography code',
    'Ethnic group: Total: All usual residents',
    'Ethnic group: Asian, Asian British or Asian Welsh',
    'Ethnic group: Black, Black British, Black Welsh, Caribbean or African',
    'Ethnic group: Mixed or Multiple ethnic groups',
    'Ethnic group: White',
    'Ethnic group: Other ethnic group'
]
diversity = diversity[cols]
diversity = diversity.rename({
    'geography' : 'lad_name',
    'geography code' : 'lad_code',
    'Ethnic group: Total: All usual residents' : 'total_pop',
    'Ethnic group: Asian, Asian British or Asian Welsh' : 'asian',
    'Ethnic group: Black, Black British, Black Welsh, Caribbean or African' : 'black',
    'Ethnic group: Mixed or Multiple ethnic groups': 'mixed',
    'Ethnic group: White' : 'white',
    'Ethnic group: Other ethnic group' : 'other'
}, axis=1)

exclude = ['lad_name', 'lad_code', 'total_pop']
for col in diversity.columns:
    if col in exclude:
        continue 
    diversity[col] = (diversity[col] / diversity['total_pop'])

eth_cols = ['asian', 'black', 'mixed', 'white', 'other']
diversity['simpsons_index'] = 1 - (diversity[eth_cols]**2).sum(axis=1)

In [90]:
diversity.head()

,lad_name,lad_code,total_pop,asian,black,mixed,white,other,simpsons_index
0,Hartlepool,E06000001,92338,0.017328,0.004819,0.007267,0.964587,0.006000,0.069160
1,Middlesbrough,E06000002,143922,0.104848,0.026514,0.020852,0.823689,0.024096,0.308824
2,Redcar and Cleveland,E06000003,136530,0.008496,0.001941,0.008679,0.976987,0.003897,0.045330
3,Stockton-on-Tees,E06000004,196593,0.046044,0.011206,0.013922,0.920363,0.008464,0.150420
4,Darlington,E06000005,107796,0.027515,0.006503,0.013655,0.943681,0.008646,0.108406

In [91]:
merged = mapped_boroughs.merge(diversity, how='left', on=['lad_code', 'lad_name'])

In [92]:
merged.head(35)

,id,lad_code,lad_name,total_pop,asian,black,mixed,white,other,simpsons_index
0,114.0,E09000014,Haringey,264238,0.087345,0.175849,0.070225,0.569869,0.096712,0.622413
1,126.0,E09000017,Hillingdon,305907,0.333232,0.078308,0.043670,0.481803,0.062986,0.644815
2,9.0,E09000003,Barnet,389344,0.192560,0.078725,0.053652,0.577284,0.097780,0.611027
3,129.0,E09000018,Hounslow,288181,0.367290,0.072212,0.046894,0.440983,0.072621,0.657944
4,139.0,E09000021,Kingston upon Thames,168065,0.178133,0.028209,0.053527,0.683254,0.056877,0.494537
5,160.0,E09000024,Merton,215187,0.185973,0.106359,0.059320,0.602346,0.046002,0.585646
6,171.0,E09000025,Newham,351030,0.422149,0.174635,0.046774,0.307515,0.048927,0.692146
7,8.0,E09000002,Barking and Dagenham,218871,0.258522,0.213857,0.042582,0.449009,0.036030,0.682711
8,35.0,E09000006,Bromley,329991,0.082751,0.076211,0.053759,0.764551,0.022728,0.399399
9,109.0,E09000012,Hackney,259147,0.103744,0.210865,0.067479,0.531393,0.086518,0.650355
10,122.0,E09000016,Havering,262052,0.107421,0.082300,0.037195,0.752957,0.020126,0.412954
11,201.0,E09000027,Richmond upon Thames,195277,0.089447,0.018881,0.054599,0.804555,0.032518,0.340296
12,112.0,E09000013,Hammersmith and Fulham,183156,0.105407,0.122589,0.067254,0.631587,0.073162,0.565083
13,142.0,E09000022,Lambeth,317650,0.072567,0.239714,0.080686,0.550222,0.056811,0.624789
14,241.0,E09000028,Southwark,307640,0.099272,0.251264,0.072003,0.514302,0.063158,0.653331
15,293.0,E09000033,Westminster,204236,0.167659,0.080573,0.065292,0.551969,0.134506,0.638373
16,17.0,E09000004,Bexley,246475,0.099134,0.122020,0.035460,0.718791,0.024595,0.456761
17,44.0,E09000007,Camden,210136,0.181035,0.089904,0.066328,0.595157,0.067575,0.595965
18,68.0,E09000008,Croydon,390724,0.175282,0.226352,0.076128,0.483679,0.038559,0.676813
19,135.0,E09000019,Islington,216590,0.099414,0.132707,0.074939,0.622162,0.070779,0.574795
20,147.0,E09000023,Lewisham,300553,0.089592,0.267750,0.080695,0.514881,0.047083,0.646453
21,272.0,E09000030,Tower Hamlets,310306,0.444258,0.073131,0.049657,0.394018,0.038936,0.638055
22,59.0,E09000001,City of London,8584,0.168336,0.027027,0.054753,0.693733,0.056151,0.483517
23,30.0,E09000005,Brent,339821,0.328158,0.175077,0.050759,0.346362,0.099644,0.729188
24,78.0,E09000009,Ealing,367116,0.303013,0.107571,0.052193,0.431643,0.105580,0.696425
25,107.0,E09000011,Greenwich,289065,0.131555,0.209648,0.059838,0.556989,0.041970,0.623162
26,117.0,E09000015,Harrow,261205,0.452334,0.073318,0.037645,0.364591,0.072112,0.650474
27,196.0,E09000026,Redbridge,310261,0.473256,0.084110,0.041049,0.348010,0.053574,0.643288
28,280.0,E09000032,Wandsworth,327506,0.116987,0.100951,0.062894,0.678125,0.041044,0.510629
29,91.0,E09000010,Enfield,329985,0.115075,0.183378,0.059269,0.520884,0.121393,0.663561
30,136.0,E09000020,Kensington and Chelsea,143373,0.118746,0.078669,0.066435,0.637456,0.098694,0.559206
31,255.0,E09000029,Sutton,209636,0.175480,0.059460,0.048474,0.682826,0.033759,0.495930
32,279.0,E09000031,Waltham Forest,278428,0.199495,0.149579,0.064588,0.528050,0.058288,0.651422

In [104]:
path = r'C:\Users\fergu\Documents\GitHub\london_sport2\exploration\data\boroughs\land-area-population-density-london.xlsx'
dense = pd.read_excel(path, sheet_name = 'Borough', skiprows=1)
cols = ['Code', 'Area name', 'Population per square kilometre']
dense = dense[cols]
dense = dense.rename({
    'Code' : 'lad_code', 
    'Area name' : 'lad_name',
    'Population per square kilometre' : 'pop_per_km2'
}, axis=1)
dense.head()

c:\Users\fergu\Documents\GitHub\london_sport2\.venv\Lib\site-packages\openpyxl\worksheet\_reader.py:329: UserWarning: Data Validation extension is not supported and will be removed
  warn(msg)

    lad_code              lad_name  pop_per_km2
0        NaN                   NaN          NaN
1  E09000001        City of London  2854.403716
2  E09000002  Barking and Dagenham  6214.914626
3  E09000003                Barnet   4784.42728
4  E09000004                Bexley  4268.804035

In [ ]:
# dense.to_csv('pop_density.csv', index=False)

In [ ]:
# diversity.to_csv('ethnic_diversity.csv', index=False)

In [161]:
path = r'C:\Users\fergu\Documents\GitHub\london_sport2\exploration\data\active_places\active_places.csv'
places = pd.read_csv(path)
print(len(places))
places.head()

124633

,ID,name,lad_code,lad_name,facility_id,facility_type_id,facility_type,facility_subtype_id,facility_subtype_name,year_built,year_built_estimated,is_refurbished,year_refurbished,status,closure_date,meets_active_places_criteria,associated_facilities
0,1000465,ENERGIE FITNESS CLUB (WEMBLEY) (CLOSED),E09000005,Brent,2015209,2,Health and Fitness Gym,2001,Health and Fitness Gym,2004.0,False,False,NaN,Closed,2012-01-01T00:00:00,True,2
1,1000465,ENERGIE FITNESS CLUB (WEMBLEY) (CLOSED),E09000005,Brent,4000516,12,Studio,12001,Fitness Studio,2004.0,False,False,NaN,Closed,2012-01-01T00:00:00,True,2
2,1003505,VIRGIN ACTIVE PURE FITNESS (NOTTINGHAM) (CLOSED),E06000018,Nottingham,4002759,12,Studio,12001,Fitness Studio,2001.0,False,True,2005.0,Closed,2006-09-01T00:00:00,False,2
3,1003505,VIRGIN ACTIVE PURE FITNESS (NOTTINGHAM) (CLOSED),E06000018,Nottingham,4017299,2,Health and Fitness Gym,2001,Health and Fitness Gym,2001.0,False,True,2003.0,Closed,2006-09-01T00:00:00,True,2
4,1003510,GOSPORT WORKOUT (CLOSED),E07000088,Gosport,2017304,2,Health and Fitness Gym,2001,Health and Fitness Gym,2000.0,False,True,2016.0,Closed,2018-11-14T00:00:00,True,1

In [162]:
places = places[places['status'] == 'Operational']
places = places.groupby(['lad_code', 'lad_name'])['status'].count()
places = places.to_frame().reset_index()
places.to_csv('active_operational_places.csv', index=False)

In [163]:
places.head()

    lad_code              lad_name  status
0  E06000001            Hartlepool     163
1  E06000002         Middlesbrough     189
2  E06000003  Redcar and Cleveland     225
3  E06000004      Stockton-on-Tees     307
4  E06000005            Darlington     200

In [ ]:
imd, meta = get_2022_data()

Data Collected...
Data Shape: (16748, 116)

<bound method NDFrame.head of         wt_final   wt_time  xStrata  Reg9  LondInOut  LA_2023  Age9  nadult  \
10      0.589497  0.476685    117.0   3.0        1.0    114.0   5.0     1.0
33      0.962646  1.165975    129.0   3.0        2.0    126.0   NaN     1.0
52      3.840907  3.882306      9.0   3.0        2.0      9.0   3.0     2.0
53      1.506097  1.525295      9.0   3.0        2.0      9.0   3.0     1.0
54      1.656646  1.347375    132.0   3.0        2.0    129.0   6.0     1.0
...          ...       ...      ...   ...        ...      ...   ...     ...
172963  1.571215  2.877129    300.0   3.0        1.0    293.0   4.0     2.0
172964  2.250045  3.803436    300.0   3.0        1.0    293.0   4.0     3.0
172965  0.717516  1.274215    300.0   3.0        1.0    293.0   4.0     1.0
172966  0.853155  1.499188    300.0   3.0        1.0    293.0   3.0     2.0
172967  0.918388  1.363505    300.0   3.0        1.0    293.0   4.0     1.0

        nchild  Disab3  ...  MONTHS_12_BASESOFTBALL_F13  \
10         0.0     2.0  ...                         0.0
33         0.0     3.0  ...                         0.0
52         1.0     3.0  ...                         0.0
53         0.0     2.0  ...                         0.0
54         0.0     1.0  ...                         0.0
...        ...     ...  ...                         ...
172963     1.0     3.0  ...                         0.0
172964     1.0     3.0  ...                         0.0
172965     0.0     3.0  ...                         0.0
172966     0.0     3.0  ...                         0.0
172967     1.0     3.0  ...                         0.0

        MONTHS_12_LACROSSE_F14  MONTHS_12_GOALBALL_F15  \
10                         0.0                     0.0
33                         0.0                     0.0
52                         0.0                     0.0
53                         0.0                     0.0
54                         0.0                     0.0
...                        ...                     ...
172963                     0.0                     0.0
172964                     0.0                     0.0
172965                     0.0                     0.0
172966                     0.0                     0.0
172967                     0.0                     0.0

        MONTHS_12_HANDBALL_F16  MEMS7_IN_SPORTCOUNT_A01  \
10                         0.0                      NaN
33                         0.0                      NaN
52                         0.0                      NaN
53                         0.0                      NaN
54                         0.0                      0.0
...                        ...                      ...
172963                     0.0                    450.0
172964                     0.0                      NaN
172965                     0.0                      NaN
172966                     0.0                      NaN
172967                     0.0                    715.0

        MEMS7_OUT_SPORTCOUNT_A01  WHOWITHA_SPORTCOUNT_A01  \
10                           NaN                      0.0
33                           NaN                      0.0
52                           NaN                      0.0
53                           NaN                      0.0
54                           0.0                      0.0
...                          ...                      ...
172963                     480.0                      1.0
172964                       NaN                      0.0
172965                       NaN                      0.0
172966                       NaN                      0.0
172967                     150.0                      1.0

        WHOWITHB_SPORTCOUNT_A01  WHOWITHC_SPORTCOUNT_A01  \
10                          0.0                      0.0
33                          0.0                      0.0
52                          0.0                      0.0
53                          0.0                      0.0
54                          0.0                      0.0
...                         ...                      ...
172963                      1.0                      0.0
172964                      0.0                      0.0
172965                      0.0                      0.0
172966                      0.0                      0.0
172967                      0.0                      1.0

        WHOWITHD_SPORTCOUNT_A01
10                          0.0
33                          0.0
52                          0.0
53                          0.0
54                          0.0
...                         ...
172963                      1.0
172964                      0.0
172965                      0.0
172966                      0.0
172967                      0.0

[16748 rows x 116 columns]>

In [166]:
imd.head()

,wt_final,wt_time,xStrata,Reg9,LondInOut,LA_2023,Age9,nadult,nchild,Disab3,...,MONTHS_12_BASESOFTBALL_F13,MONTHS_12_LACROSSE_F14,MONTHS_12_GOALBALL_F15,MONTHS_12_HANDBALL_F16,MEMS7_IN_SPORTCOUNT_A01,MEMS7_OUT_SPORTCOUNT_A01,WHOWITHA_SPORTCOUNT_A01,WHOWITHB_SPORTCOUNT_A01,WHOWITHC_SPORTCOUNT_A01,WHOWITHD_SPORTCOUNT_A01
10,0.589497,0.476685,117.0,3.0,1.0,114.0,5.0,1.0,0.0,2.0,...,0.0,0.0,0.0,0.0,NaN,NaN,0.0,0.0,0.0,0.0
33,0.962646,1.165975,129.0,3.0,2.0,126.0,NaN,1.0,0.0,3.0,...,0.0,0.0,0.0,0.0,NaN,NaN,0.0,0.0,0.0,0.0
52,3.840907,3.882306,9.0,3.0,2.0,9.0,3.0,2.0,1.0,3.0,...,0.0,0.0,0.0,0.0,NaN,NaN,0.0,0.0,0.0,0.0
53,1.506097,1.525295,9.0,3.0,2.0,9.0,3.0,1.0,0.0,2.0,...,0.0,0.0,0.0,0.0,NaN,NaN,0.0,0.0,0.0,0.0
54,1.656646,1.347375,132.0,3.0,2.0,129.0,6.0,1.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [167]:
imd = imd.groupby('LA_2023')['IMD10'].mean()
imd = imd.to_frame().reset_index()
imd.head()

   LA_2023     IMD10
0      8.0  2.782435
1      9.0  6.601227
2     17.0  6.671400
3     30.0  4.262327
4     35.0  7.526104

In [191]:
features = [
    'lifesat', 'lone', 'worthw', 'indev', 'happy', 'comm1', 'comm2',
    'anxious', 'motivex2a', 'motivex2b', 'motivex2c', 'motivex2d', 'inclus_a',
    'inclus_b', 'inclus_c', 'VolAny', 'IMD10']

def make_dfs(features):
    dfs = []
    df, meta = get_2022_data()
    print(f'Initial DataFrame has length: {len(df)}')
    for f in features:
        series = df.groupby('LA_2023')[f].mean()
        print(f'Series: {f} has length: {len(series)}')
        # May want to built in more checks to see that the idx are aligned
        # print(series.index)
        dfs.append(series)
    combined = pd.concat(dfs, axis=1)
    return combined.reset_index()
combined = make_dfs(features)

Data Collected...
Data Shape: (16748, 116)
Initial DataFrame has length: 16748
Series: lifesat has length: 33
Series: lone has length: 33
Series: worthw has length: 33
Series: indev has length: 33
Series: happy has length: 33
Series: comm1 has length: 33
Series: comm2 has length: 33
Series: anxious has length: 33
Series: motivex2a has length: 33
Series: motivex2b has length: 33
Series: motivex2c has length: 33
Series: motivex2d has length: 33
Series: inclus_a has length: 33
Series: inclus_b has length: 33
Series: inclus_c has length: 33
Series: VolAny has length: 33
Series: IMD10 has length: 33

In [192]:
combined.head()

,LA_2023,lifesat,lone,worthw,indev,happy,comm1,comm2,anxious,motivex2a,motivex2b,motivex2c,motivex2d,inclus_a,inclus_b,inclus_c,VolAny,IMD10
0,8.0,6.603448,3.307368,6.856322,3.716763,6.687861,2.930636,2.806061,4.068966,1.923077,2.279736,2.886667,2.680804,2.280802,2.422287,2.388889,0.131443,2.782435
1,9.0,6.956284,3.470085,7.291209,3.664835,7.054645,3.230769,3.039773,3.568306,1.711579,2.198732,2.954447,2.731183,2.269006,2.403030,2.293769,0.202703,6.601227
2,17.0,6.827586,3.429175,7.321839,3.695402,7.051724,3.247126,2.863905,3.580460,1.845833,2.357294,2.912951,2.823404,2.252841,2.328446,2.318052,0.176623,6.671400
3,30.0,6.787879,3.425887,6.853535,3.722222,6.848485,3.115578,2.872449,3.909091,1.716049,2.146444,2.874730,2.588865,2.241667,2.360231,2.221902,0.139949,4.262327
4,35.0,6.772487,3.583851,6.978836,3.666667,6.804233,3.375661,2.994652,4.047619,1.752643,2.217021,2.853503,2.728051,2.198777,2.325228,2.214067,0.220670,7.526104

In [ ]:
# combined.to_csv('social_environmental.csv', index=False)