In [111]:
from pathlib import Path
import pandas as pd
import numpy as np
import sys
ROOT = Path.cwd().parent.parent
sys.path.append(str(ROOT))
from src.loading_data.load_data import get_data
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
import statsmodels.api as sm
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import OneHotEncoder

In [112]:
df = get_data()
df.head()

DataFrame Cleaned Sucessfully...
DataFrame Information:
>>> Columns:
Index(['Gend3', 'Disab3', 'Age9', 'Eth7', 'NSSEC5', 'Educ6', 'MEMS7_ALL',
       'year', 'IMD10', 'nchild', 'VolAny', 'Motiva_POP', 'motivb_POP',
       'motivc_POP', 'motivd_POP', 'WorkStat10', 'active'],
      dtype='str')
>>> Shape (86089, 17)
--------------------------
Columns NOT in Master.csv:
>>> ['nadults', 'motivex2a', 'motivex2b', 'motivex2c', 'motivex2d', 'inclus_a', 'inclus_b', 'inclus_c', 'comm2', 'limfreti1', 'limfreti2', 'limfreti3', 'limfreti4', 'limfreti5', 'limfreti6', 'limfreti7', 'limfreti8']
Unhealthy Columns:
>>> ['motive_POP', 'comm1', 'anxious', 'happy', 'lifesat', 'lone', 'worthw', 'indev', 'indevtry']

,Gend3,Disab3,Age9,Eth7,NSSEC5,Educ6,MEMS7_ALL,year,IMD10,nchild,VolAny,Motiva_POP,motivb_POP,motivc_POP,motivd_POP,WorkStat10,active
19887,1.0,3.0,2.0,4.0,1.0,1.0,0.0,2016/17,2.0,1.0,1.0,1.0,2.0,2.0,4.0,2.0,False
19888,1.0,3.0,4.0,4.0,2.0,1.0,90.0,2016/17,4.0,0.0,0.0,2.0,2.0,4.0,4.0,2.0,False
19889,2.0,3.0,4.0,1.0,1.0,1.0,1200.0,2016/17,7.0,0.0,0.0,2.0,2.0,2.0,4.0,1.0,True
19890,1.0,3.0,4.0,2.0,1.0,1.0,0.0,2016/17,4.0,1.0,0.0,2.0,3.0,4.0,4.0,1.0,False
19891,2.0,1.0,4.0,2.0,1.0,1.0,30.0,2016/17,4.0,1.0,0.0,1.0,1.0,2.0,3.0,2.0,False

In [113]:
dont_encode = ['nchild', 'active', 'MEMS7_ALL', 'year']
discrete_variables = [c for c in df.columns if c not in dont_encode]
# df_encoded = pd.get_dummies(df, columns = discrete_variables, drop_first=True )
for c in discrete_variables:
    print(c, df[c].value_counts().index[0])

reference_categories = [f'{c}_{df[c].value_counts().index[0]}' for c in discrete_variables]
reference_categories

Gend3 2.0
Disab3 3.0
Age9 4.0
Eth7 1.0
NSSEC5 1.0
Educ6 1.0
IMD10 2.0
VolAny 0.0
Motiva_POP 2.0
motivb_POP 2.0
motivc_POP 2.0
motivd_POP 4.0
WorkStat10 1.0

['Gend3_2.0',
 'Disab3_3.0',
 'Age9_4.0',
 'Eth7_1.0',
 'NSSEC5_1.0',
 'Educ6_1.0',
 'IMD10_2.0',
 'VolAny_0.0',
 'Motiva_POP_2.0',
 'motivb_POP_2.0',
 'motivc_POP_2.0',
 'motivd_POP_4.0',
 'WorkStat10_1.0']

In [114]:
encoder = OneHotEncoder(drop='first', handle_unknown = 'ignore', sparse_output = False).set_output(transform='pandas')

In [115]:
encoded = encoder.fit_transform(df[discrete_variables])
df_encoded = pd.concat([df, encoded], axis=1).drop(columns=discrete_variables+['MEMS7_ALL'])
df_encoded.head()

,year,nchild,active,Gend3_2.0,Gend3_3.0,Disab3_2.0,Disab3_3.0,Age9_3.0,Age9_4.0,Age9_5.0,...,motivd_POP_5.0,WorkStat10_2.0,WorkStat10_3.0,WorkStat10_4.0,WorkStat10_5.0,WorkStat10_6.0,WorkStat10_7.0,WorkStat10_8.0,WorkStat10_9.0,WorkStat10_10.0
19887,2016/17,1.0,False,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
19888,2016/17,0.0,False,0.0,0.0,0.0,1.0,0.0,1.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
19889,2016/17,0.0,True,1.0,0.0,0.0,1.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
19890,2016/17,1.0,False,0.0,0.0,0.0,1.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
19891,2016/17,1.0,False,1.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [116]:
df_encoded_2016 = df_encoded[df_encoded['year'] == '2016/17']
df_encoded_2016 = df_encoded_2016.drop(columns=['year'])

In [117]:
Y = df_encoded_2016['active']
X = df_encoded_2016.drop(columns=['active'])

In [118]:
X.columns

Index(['nchild', 'Gend3_2.0', 'Gend3_3.0', 'Disab3_2.0', 'Disab3_3.0',
       'Age9_3.0', 'Age9_4.0', 'Age9_5.0', 'Age9_6.0', 'Age9_7.0', 'Age9_8.0',
       'Age9_9.0', 'Eth7_2.0', 'Eth7_3.0', 'Eth7_4.0', 'Eth7_5.0', 'Eth7_6.0',
       'Eth7_7.0', 'NSSEC5_2.0', 'NSSEC5_3.0', 'NSSEC5_4.0', 'NSSEC5_5.0',
       'Educ6_2.0', 'Educ6_3.0', 'Educ6_4.0', 'Educ6_5.0', 'Educ6_6.0',
       'IMD10_2.0', 'IMD10_3.0', 'IMD10_4.0', 'IMD10_5.0', 'IMD10_6.0',
       'IMD10_7.0', 'IMD10_8.0', 'IMD10_9.0', 'IMD10_10.0', 'VolAny_1.0',
       'Motiva_POP_2.0', 'Motiva_POP_3.0', 'Motiva_POP_4.0', 'Motiva_POP_5.0',
       'motivb_POP_2.0', 'motivb_POP_3.0', 'motivb_POP_4.0', 'motivb_POP_5.0',
       'motivc_POP_2.0', 'motivc_POP_3.0', 'motivc_POP_4.0', 'motivc_POP_5.0',
       'motivd_POP_2.0', 'motivd_POP_3.0', 'motivd_POP_4.0', 'motivd_POP_5.0',
       'WorkStat10_2.0', 'WorkStat10_3.0', 'WorkStat10_4.0', 'WorkStat10_5.0',
       'WorkStat10_6.0', 'WorkStat10_7.0', 'WorkStat10_8.0', 'WorkStat10_9.0',
       'WorkStat10_10.0'],
      dtype='str')

In [119]:
Xtrain, Xtest, Ytrain, Ytest = train_test_split(X, Y, test_size = 0.25, random_state = 42)
scaler = StandardScaler()
continuous_cols = ['nchild']
Xtrain[continuous_cols] = scaler.fit_transform(Xtrain[continuous_cols])
Xtest[continuous_cols] = scaler.transform(Xtest[continuous_cols])

In [120]:
model = LogisticRegression()
model.fit(Xtrain, Ytrain)

LogisticRegression()

In [128]:
print(len(model.coef_[0]), len(model.feature_names_in_))

62 62

In [129]:
for idx, name in enumerate(model.feature_names_in_):
    print(f'{name} : {model.coef_[0][idx]}')

nchild : -0.11815260294725356
Gend3_2.0 : -0.07204388304986122
Gend3_3.0 : 0.0
Disab3_2.0 : 0.33830653607745786
Disab3_3.0 : 0.2016554568519471
Age9_3.0 : -0.12997242741180245
Age9_4.0 : -0.055911792585367555
Age9_5.0 : -0.02368665659895195
Age9_6.0 : -0.18900825105740024
Age9_7.0 : -0.4302630293888496
Age9_8.0 : -0.21323853158469985
Age9_9.0 : -0.7539947303639186
Eth7_2.0 : -0.42459729629202564
Eth7_3.0 : -0.9880581575172939
Eth7_4.0 : -0.9031245389323146
Eth7_5.0 : -0.981280354294717
Eth7_6.0 : -0.22401998732411704
Eth7_7.0 : -0.5190672984550289
NSSEC5_2.0 : -0.15241465229007944
NSSEC5_3.0 : -0.4253803497368136
NSSEC5_4.0 : -0.43865628756663994
NSSEC5_5.0 : -0.9672332619486183
Educ6_2.0 : -0.1469049582890792
Educ6_3.0 : -0.2920644536398914
Educ6_4.0 : -0.3002406327820187
Educ6_5.0 : -0.3116204421361882
Educ6_6.0 : -0.48066436100085425
IMD10_2.0 : 0.07680027207714883
IMD10_3.0 : 0.06067847026512626
IMD10_4.0 : -0.08540407877135305
IMD10_5.0 : 0.130230988339855
IMD10_6.0 : 0.1851106847173221
IMD10_7.0 : -0.06799037398392747
IMD10_8.0 : -0.00022914335569013914
IMD10_9.0 : -0.04603499130441762
IMD10_10.0 : 0.18092845529769958
VolAny_1.0 : 0.4413562525636054
Motiva_POP_2.0 : -0.33554875467632916
Motiva_POP_3.0 : -0.7958455915945984
Motiva_POP_4.0 : -1.0078086872790246
Motiva_POP_5.0 : -1.4401255286595864
motivb_POP_2.0 : -0.48949598781406706
motivb_POP_3.0 : -0.8148058110612865
motivb_POP_4.0 : -0.7483053331980781
motivb_POP_5.0 : -0.7071124484915606
motivc_POP_2.0 : 0.11398469289435992
motivc_POP_3.0 : -0.03634340630060992
motivc_POP_4.0 : -0.06580659050095133
motivc_POP_5.0 : -0.31508772476636643
motivd_POP_2.0 : 0.49250079272931685
motivd_POP_3.0 : 0.31392694921638425
motivd_POP_4.0 : 0.32680799402492305
motivd_POP_5.0 : 0.4005305787140789
WorkStat10_2.0 : 0.07934204946504056
WorkStat10_3.0 : 0.5005789756930304
WorkStat10_4.0 : -0.03561811575913731
WorkStat10_5.0 : 0.07787375493433922
WorkStat10_6.0 : 0.18730728650361433
WorkStat10_7.0 : -0.6148046432714059
WorkStat10_8.0 : 0.5353134177636294
WorkStat10_9.0 : 0.24431631087557756
WorkStat10_10.0 : 0.22182346364271213